(load "~/quicklisp/setup.lisp")
(ql:quickload "sdl2")

(defun basic-screen ()
  (sdl2:with-init (:video)
    (sdl2:with-window (win :title "Hello SDL2" :w 800 :h 600 :flags '(:shown))
      (sdl2:with-renderer (renderer win :index -1 :flags '(:accelerated))
        (sdl2:set-render-draw-color renderer 255 255 255 255)
        (sdl2:render-clear renderer)
        (sdl2:render-present renderer)
        (sdl2:with-event-loop (:method :poll)
          (:quit () t)
          (:idle ()
                 (sdl2:render-clear renderer)
                 (sdl2:render-present renderer))))))
  (sb-ext:gc :full t))

(basic-screen)